services:
  app:
    build: .
    container_name: premiumcoffe-app
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CLOUDINARY_ENABLED: ${CLOUDINARY_ENABLED}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_FOLDER: ${CLOUDINARY_FOLDER}
    ports:
      - "8080:8080"