server.port=8080
spring.application.name=PremiumCoffe

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false